version: '3.8'
services:
  tmserver:
    image: fanyx/tmserver:latest
    container_name: trackmania_tmserver
    depends_on:
     - db
    restart: always
    environment:
     - SERVER_LOGIN="butterlan"
     - SERVER_LOGIN_PASSWORD=""
     - SERVER_SA_PASSWORD="butteradmin"
     - SERVER_ADM_PASSWORD=""
     - SERVER_PORT=2350
     - SERVER_P2P_PORT=3450
     - SERVER_NAME="ButterMania"
     - SERVER_COMMENT="Trackmania Server an der Butterlan"
     - SERVER_PASSWORD=""
     - HIDE_SERVER=0
     - MAX_PLAYERS=32
     - PACKMASK=stadium
     - GAMEMODE=1
     - CHATTIME=10000
     - FINISHTIMEOUT=1
     - DISABLERESPAWN=0
     - ROUNDS_POINTSLIMIT=30
     - TIMEATTACK_LIMIT=180000
     - TEAM_POINTSLIMIT=50
     - TEAM_MAXPOINTS=6
     - LAPS_NBLAPS=5
     - LAPS_TIMELIMIT=0
     - CUP_POINTSLIMIT=100
     - CUP_ROUNDSPERCHALLENGE=5
     - CUP_NBWINNERS=3
     - CUP_WARMUPDURATION=2
     # XASECO
     - MASTERADMIN_LOGIN="butteradmin"
     - MYSQL_HOST=db
     - MYSQL_LOGIN="trackmania"
     - MYSQL_DATABASE="trackmania"
     - MYSQL_PASSWORD=""
    volumes:
     - ./tracks:/var/lib/tmserver/GameData/Tracks/Challenges/Custom # => Custom tracks
     - ./playlist.txt:/var/lib/tmserver/playlist.txt # => Custom playlist
     - ./blacklist:/var/lib/xaseco/blacklist # => Plugin blacklist
     - ./plugins:/var/lib/xaseco/plugins/custom # => Custom plugins
     - ./config:/var/lib/xaseco/config # => Custom configuration files
    ports:
     - "2350:2350"
     - "2350:2350/udp"
     - "3450:3450/udp"
  db:
    image: mysql:5
    container_name: trackmania_db
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=trackmania
     - MYSQL_USER=trackmania
     - MYSQL_PASSWORD=
    volumes:
     - trackmania-db:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: trackmania_phpmyadmin
    depends_on:
     - db
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - "8080:80"

volumes:
  trackmania-db: